/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ClientRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.ClientOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 
 */
public class ClientWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private ClientOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;
    private Network network;
//    private UserAccount sender;
//    private UserAccount receiver;
    /**
     * Creates new form ClientWorkAreaJPanel
     */
    public ClientWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, ClientOrganization organization, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.system = system;
        this.network = network;
//        this.sender = sender;
//        this.receiver = receiver;
        if(userAccount.getApplication() != null) {
            if(userAccount.getApplication().getLawyer() != null) {
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewProblemJButton = new javax.swing.JButton();
        askJButton = new javax.swing.JButton();
        rsvJButton = new javax.swing.JButton();
        applyButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 236, 236));

        viewProblemJButton.setBackground(new java.awt.Color(51, 51, 51));
        viewProblemJButton.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        viewProblemJButton.setForeground(new java.awt.Color(255, 51, 51));
        viewProblemJButton.setText("Concerns");
        viewProblemJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewProblemJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewProblemJButtonMouseExited(evt);
            }
        });
        viewProblemJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProblemJButtonActionPerformed(evt);
            }
        });

        askJButton.setBackground(new java.awt.Color(51, 51, 51));
        askJButton.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        askJButton.setForeground(new java.awt.Color(255, 51, 51));
        askJButton.setText("Lawyers");
        askJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                askJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                askJButtonMouseExited(evt);
            }
        });
        askJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                askJButtonActionPerformed(evt);
            }
        });

        rsvJButton.setBackground(new java.awt.Color(51, 51, 51));
        rsvJButton.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        rsvJButton.setForeground(new java.awt.Color(255, 51, 51));
        rsvJButton.setText("Reservations");
        rsvJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rsvJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rsvJButtonMouseExited(evt);
            }
        });
        rsvJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rsvJButtonActionPerformed(evt);
            }
        });

        applyButton.setBackground(new java.awt.Color(51, 51, 51));
        applyButton.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        applyButton.setForeground(new java.awt.Color(255, 51, 51));
        applyButton.setText("NPO");
        applyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                applyButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                applyButtonMouseExited(evt);
            }
        });
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("CLIENT DASHBOARD");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(667, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/survivor.gif"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewProblemJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rsvJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(askJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(applyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(askJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(viewProblemJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(rsvJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(applyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)))
                .addContainerGap(345, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewProblemJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProblemJButtonActionPerformed
        // TODO add your handling code here:
        ManageProblemJPanel mpjp = new ManageProblemJPanel(userProcessContainer, userAccount);
        userProcessContainer.add("ManageProblemJPanel", mpjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewProblemJButtonActionPerformed

    private void askJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_askJButtonActionPerformed

        RetrieveLawyerJPanel rljp = new RetrieveLawyerJPanel(userProcessContainer, userAccount, system);
        userProcessContainer.add("RetrieveLawyerJPanel", rljp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_askJButtonActionPerformed

    private void rsvJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rsvJButtonActionPerformed
        // TODO add your handling code here:
        ManageReservationJPanel mrjp = new ManageReservationJPanel(userProcessContainer, userAccount);
        userProcessContainer.add("ManageReservationJPanel", mrjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_rsvJButtonActionPerformed

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        // TODO add your handling code here:

        ApplyForNPOJPanel afpb =new ApplyForNPOJPanel (userProcessContainer,userAccount,enterprise,organization,network,system);
        userProcessContainer.add("ApplyForProBonoJPanel", afpb);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_applyButtonActionPerformed

    private void askJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_askJButtonMouseEntered
        // TODO add your handling code here:
        askJButton.setBackground(Color.ORANGE);
    }//GEN-LAST:event_askJButtonMouseEntered

    private void askJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_askJButtonMouseExited
        // TODO add your handling code here:
        askJButton.setBackground(Color.darkGray);
    }//GEN-LAST:event_askJButtonMouseExited

    private void viewProblemJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewProblemJButtonMouseEntered
        // TODO add your handling code here:
        viewProblemJButton.setBackground(Color.ORANGE);
    }//GEN-LAST:event_viewProblemJButtonMouseEntered

    private void viewProblemJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewProblemJButtonMouseExited
        // TODO add your handling code here:
        viewProblemJButton.setBackground(Color.darkGray);
    }//GEN-LAST:event_viewProblemJButtonMouseExited

    private void rsvJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rsvJButtonMouseEntered
        // TODO add your handling code here:
        rsvJButton.setBackground(Color.ORANGE);
    }//GEN-LAST:event_rsvJButtonMouseEntered

    private void rsvJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rsvJButtonMouseExited
        // TODO add your handling code here:
        rsvJButton.setBackground(Color.darkGray);
    }//GEN-LAST:event_rsvJButtonMouseExited

    private void applyButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applyButtonMouseEntered
        // TODO add your handling code here:
        applyButton.setBackground(Color.ORANGE);
    }//GEN-LAST:event_applyButtonMouseEntered

    private void applyButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applyButtonMouseExited
        // TODO add your handling code here:
        applyButton.setBackground(Color.darkGray);
    }//GEN-LAST:event_applyButtonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JButton askJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton rsvJButton;
    private javax.swing.JButton viewProblemJButton;
    // End of variables declaration//GEN-END:variables
}
