/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ClientRole;

import Business.Problem.RespondedProblem;
import Business.Schedule.DailySchedule;
import Business.Schedule.TimeSlot;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 
 */
public class ViewProblemJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private RespondedProblem problem;
    /**
     * Creates new form ViewProblemJPanel
     */
    public ViewProblemJPanel(JPanel userProcessContainer, RespondedProblem problem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.problem = problem;
        msgjLabel.setText(problem.getMessage());
        receiverJLabel.setText(problem.getReceiver().getEmployee().getName());
        statusjLabel.setText(problem.getStatus());
        replyJLabel.setText(problem.getFeedback());
        if(problem.getStatus().equals("Meeting Suggested")) {
            populateDateComboBox();
            dateJComboBox.setEnabled(true);
            timeJComboBox.setEnabled(true);
            reserveJButton.setEnabled(true);
        }
        
    }
    
    private void populateDateComboBox() {
        dateJComboBox.removeAllItems();
        Date today = new Date();
        Calendar cal = Calendar.getInstance();
        for(DailySchedule ds : problem.getReceiver().getEmployee().getSchedule().getDailyScheduleList()) {
            if(ds.getDate().after(today)) {
                cal.setTime(ds.getDate());
                if(cal.get(Calendar.DAY_OF_WEEK) == Calendar.SATURDAY || cal.get(Calendar.DAY_OF_WEEK) == Calendar.SUNDAY){
                    continue;
                }
                boolean available = false;
                for(TimeSlot ts : ds.getTimeSlotList()) {
                    if(!ts.isOccupied()) {
                        available = true;
                        break;
                    }
                }
                if(available) {
                    dateJComboBox.addItem(ds);
                }
            }
        }
    }
    
    private void populateTimeComboBox(DailySchedule ds) {
        timeJComboBox.removeAllItems();
        for(TimeSlot ts : ds.getTimeSlotList()) {
            if(!ts.isOccupied()) {
                timeJComboBox.addItem(ts);
            }
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msgjLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        statusjLabel = new javax.swing.JLabel();
        reserveJButton = new javax.swing.JButton();
        receiverJLabel = new javax.swing.JLabel();
        dateJComboBox = new javax.swing.JComboBox();
        timeJComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        replyJLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 236, 236));

        msgjLabel.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Status:");

        jLabel3.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Receiver:");

        jLabel2.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Message:");

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back Button Arrow Icon!!!! (3).jpg"))); // NOI18N
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Reply:");

        statusjLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        reserveJButton.setBackground(new java.awt.Color(51, 51, 51));
        reserveJButton.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        reserveJButton.setForeground(new java.awt.Color(0, 153, 153));
        reserveJButton.setText("Book Appointment");
        reserveJButton.setEnabled(false);
        reserveJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reserveJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reserveJButtonMouseExited(evt);
            }
        });
        reserveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveJButtonActionPerformed(evt);
            }
        });

        receiverJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        dateJComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dateJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dateJComboBox.setEnabled(false);
        dateJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateJComboBoxActionPerformed(evt);
            }
        });

        timeJComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        timeJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        timeJComboBox.setEnabled(false);
        timeJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeJComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Date:");

        jLabel6.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Time:");

        replyJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("VIEW CONCERNS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(timeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(msgjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(statusjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(111, 111, 111)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(receiverJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(replyJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(reserveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(msgjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(statusjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(receiverJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addComponent(reserveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(replyJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(213, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageProblemJPanel mpjp = (ManageProblemJPanel) component;
        mpjp.populateProblemTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void reserveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveJButtonActionPerformed
        
        DailySchedule ds = (DailySchedule)dateJComboBox.getSelectedItem();
        TimeSlot ts = (TimeSlot)timeJComboBox.getSelectedItem();
        int number = ds.getTimeSlotList().indexOf(ts);
        
        for(DailySchedule cds : problem.getSender().getEmployee().getSchedule().getDailyScheduleList()) {
            if(cds.toString().equals(ds.toString())) {
                if(cds.getTimeSlotList().get(number).isOccupied()) {
                    JOptionPane.showMessageDialog(null, "The time slot is already occupied! Please select another one!");
                    return;
                }
                else {
                    cds.getTimeSlotList().get(number).setOccupied(true);
                    cds.getTimeSlotList().get(number).setTask("Meeting with lawyer " + problem.getReceiver().getEmployee().getName());
                    cds.getTimeSlotList().get(number).setReservation(true);
                    cds.getTimeSlotList().get(number).setProblem(problem);
                    ts.setOccupied(true);
                    ts.setTask("Meeting with client " + problem.getSender().getEmployee().getName());
                    ts.setReservation(true);
                    ts.setProblem(problem);
                    problem.setStatus("Meeting Reserved");
                    JOptionPane.showMessageDialog(null, "Your reservation was successfully made!");
                    return;
                }
            }
        }
        DailySchedule nds = problem.getSender().getEmployee().getSchedule().createDailySchedule(ds.getDate());
        nds.getTimeSlotList().get(number).setOccupied(true);
        nds.getTimeSlotList().get(number).setTask("Meeting with lawyer " + problem.getReceiver().getEmployee().getName());
        nds.getTimeSlotList().get(number).setReservation(true);
        nds.getTimeSlotList().get(number).setProblem(problem);
        ts.setOccupied(true);
        ts.setTask("Meeting with client " + problem.getSender().getEmployee().getName());
        ts.setReservation(true);
        ts.setProblem(problem);
        problem.setStatus("Meeting Reserved");
        JOptionPane.showMessageDialog(null, "Your reservation was successfully made!");
        
        dateJComboBox.setEnabled(false);
        timeJComboBox.setEnabled(false);
        reserveJButton.setEnabled(false);
    }//GEN-LAST:event_reserveJButtonActionPerformed

    private void timeJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeJComboBoxActionPerformed

    private void dateJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateJComboBoxActionPerformed
        // TODO add your handling code here:
        DailySchedule ds = (DailySchedule)dateJComboBox.getSelectedItem();
        if(ds != null) {
            populateTimeComboBox(ds);
        }
    }//GEN-LAST:event_dateJComboBoxActionPerformed

    private void reserveJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reserveJButtonMouseEntered
        // TODO add your handling code here:
        reserveJButton.setBackground(Color.ORANGE);
    }//GEN-LAST:event_reserveJButtonMouseEntered

    private void reserveJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reserveJButtonMouseExited
        // TODO add your handling code here:
        reserveJButton.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_reserveJButtonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox dateJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel msgjLabel;
    private javax.swing.JLabel receiverJLabel;
    private javax.swing.JLabel replyJLabel;
    private javax.swing.JButton reserveJButton;
    private javax.swing.JLabel statusjLabel;
    private javax.swing.JComboBox timeJComboBox;
    // End of variables declaration//GEN-END:variables
}
