/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.AssistantRole;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Schedule.DailySchedule;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 
 */
public class AssistantWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;
    /**
     * Creates new form AssistantWorkAreaJPanel
     */
    public AssistantWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise = enterprise;
        valueLabel.setText(enterprise.getName());
        addNewDay();
    }
    
    private void addNewDay() {
        SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
        Calendar c = Calendar.getInstance();
        for(int i=0; i<30; i++) {
            Date today = new Date();
            c.setTime(today);
            c.add(Calendar.DAY_OF_MONTH, i);
            Date date = c.getTime();
            for(Employee lawyer : account.getEmployee().getLawyerDirectory().getEmployeeList()) {
                boolean existing = false;
                for(DailySchedule ds : lawyer.getSchedule().getDailyScheduleList()) {
                    if(ds.toString().equals(fmt.format(date))) {
                        existing = true;
                        break;
                    }
                }
                if(!existing) {
                    lawyer.getSchedule().createDailySchedule(date);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valueLabel = new javax.swing.JLabel();
        manageScheduleJButton = new javax.swing.JButton();
        manageRequestJButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 236, 236));
        setForeground(new java.awt.Color(236, 236, 236));

        valueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        manageScheduleJButton.setBackground(new java.awt.Color(51, 51, 51));
        manageScheduleJButton.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        manageScheduleJButton.setForeground(new java.awt.Color(204, 204, 0));
        manageScheduleJButton.setText("Manage Schedules");
        manageScheduleJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageScheduleJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageScheduleJButtonMouseExited(evt);
            }
        });
        manageScheduleJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageScheduleJButtonActionPerformed(evt);
            }
        });

        manageRequestJButton.setBackground(new java.awt.Color(51, 51, 51));
        manageRequestJButton.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        manageRequestJButton.setForeground(new java.awt.Color(204, 204, 0));
        manageRequestJButton.setText("Manage Requests");
        manageRequestJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageRequestJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageRequestJButtonMouseExited(evt);
            }
        });
        manageRequestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageRequestJButtonActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 0, 255));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 51));
        jLabel11.setText("LEGAL ASSISTANT WORK AREA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(651, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/unnamed.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(manageRequestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(227, 227, 227)
                        .addComponent(manageScheduleJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageRequestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageScheduleJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(263, 263, 263))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageScheduleJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageScheduleJButtonActionPerformed

        ManageSchedulesJPanel msjp = new ManageSchedulesJPanel(userProcessContainer, account);
        userProcessContainer.add("ManageSchedulesJPanel", msjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageScheduleJButtonActionPerformed

    private void manageRequestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageRequestJButtonActionPerformed

        ManageRequestJPanel mrjp = new ManageRequestJPanel(userProcessContainer, account);
        userProcessContainer.add("ManageRequestJPanel", mrjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageRequestJButtonActionPerformed

    private void manageRequestJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageRequestJButtonMouseEntered
        // TODO add your handling code here:
        manageRequestJButton.setBackground(Color.ORANGE);
    }//GEN-LAST:event_manageRequestJButtonMouseEntered

    private void manageRequestJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageRequestJButtonMouseExited
        // TODO add your handling code here:
        manageRequestJButton.setBackground(Color.darkGray);
    }//GEN-LAST:event_manageRequestJButtonMouseExited

    private void manageScheduleJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageScheduleJButtonMouseEntered
        // TODO add your handling code here:
        manageScheduleJButton.setBackground(Color.ORANGE);
    }//GEN-LAST:event_manageScheduleJButtonMouseEntered

    private void manageScheduleJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageScheduleJButtonMouseExited
        // TODO add your handling code here:
        manageScheduleJButton.setBackground(Color.darkGray);
    }//GEN-LAST:event_manageScheduleJButtonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton manageRequestJButton;
    private javax.swing.JButton manageScheduleJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
