/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.AssistantRole;

import Business.Employee.Employee;
import Business.Schedule.DailySchedule;
import Business.Schedule.TimeSlot;
import Business.ScheduleRequest.ResolvedScheduleRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *

 */
public class ShowScheduleJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private ResolvedScheduleRequest request;
    /**
     * Creates new form ShowScheduleJPanel
     */
    public ShowScheduleJPanel(JPanel userProcessContainer, ResolvedScheduleRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        valueLabel.setText(request.getSender().toString());
        populateDateComboBox();
    }
    
    public void populateDateComboBox() {
        dateJComboBox.removeAllItems();
        Date today = new Date();
        SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
        for(DailySchedule ds : request.getSender().getEmployee().getSchedule().getDailyScheduleList()) {
            if(ds.toString().equals(fmt.format(today))) {
                dateJComboBox.addItem(ds);
                continue;
            }
            if(ds.getDate().before(today)) {
                continue;
            }
            dateJComboBox.addItem(ds);
        }
    }
    
    private void populateTable(DailySchedule ds) {
        DefaultTableModel model = (DefaultTableModel) scheduleJTable.getModel();
        model.setRowCount(0);
        for (TimeSlot ts : ds.getTimeSlotList()){
            Object[] row = new Object[3];
            row[0] = ts;
            if(ts.isOccupied()) {
                row[1] = "Occupied";
            }
            else {
                row[1] = "Available";
            }
            row[2] = ts.getTask();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        scheduleJTable = new javax.swing.JTable();
        dateJComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        viewJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        cancelJButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 236, 236));

        scheduleJTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        scheduleJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Time", "Status", "Task"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(scheduleJTable);

        dateJComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dateJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dateJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateJComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 0));
        jLabel2.setText("Date:");

        viewJButton.setBackground(new java.awt.Color(51, 51, 51));
        viewJButton.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        viewJButton.setForeground(new java.awt.Color(204, 204, 0));
        viewJButton.setText("View/Edit");
        viewJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewJButtonMouseExited(evt);
            }
        });
        viewJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewJButtonActionPerformed(evt);
            }
        });

        backJButton.setBackground(new java.awt.Color(51, 51, 51));
        backJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 51, 51));
        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back Button Arrow Icon!!!! (3).jpg"))); // NOI18N
        backJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backJButtonMouseExited(evt);
            }
        });
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        valueLabel.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N

        cancelJButton.setBackground(new java.awt.Color(51, 51, 51));
        cancelJButton.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        cancelJButton.setForeground(new java.awt.Color(204, 204, 0));
        cancelJButton.setText("Cancel");
        cancelJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelJButtonMouseExited(evt);
            }
        });
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJButtonActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 0, 255));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 51));
        jLabel6.setText("VIEW SCHEDULE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(dateJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(cancelJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(viewJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dateJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateJComboBoxActionPerformed
        // TODO add your handling code here:
        DailySchedule ds = (DailySchedule)dateJComboBox.getSelectedItem();
        if(ds != null) {
            populateTable(ds);
        }
    }//GEN-LAST:event_dateJComboBoxActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void viewJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = scheduleJTable.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a time slot to edit.");
            return;
        }

        Employee lawyer = request.getSender().getEmployee();
        DailySchedule ds = (DailySchedule)dateJComboBox.getSelectedItem();
        TimeSlot ts = (TimeSlot)scheduleJTable.getValueAt(selectedRow, 0);

        ViewLawyerScheduleJPanel vlsjp = new ViewLawyerScheduleJPanel(userProcessContainer, lawyer, ds, ts);
        userProcessContainer.add("ViewLawyerScheduleJPanel", vlsjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewJButtonActionPerformed

    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = scheduleJTable.getSelectedRow();
        if(selectedRow>=0){
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to cancel?","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
                TimeSlot ts = (TimeSlot)scheduleJTable.getValueAt(selectedRow, 0);
                if(ts.isReservation()) {
                    for(DailySchedule cds : ts.getProblem().getSender().getEmployee().getSchedule().getDailyScheduleList()) {
                        if(cds.toString().equals(dateJComboBox.getSelectedItem().toString())) {
                            for(TimeSlot cts : cds.getTimeSlotList()) {
                                if(cts.getSlot().equals(ts.getSlot())) {
                                    ts.getProblem().setStatus("Meeting Suggested");
                                    cts.setOccupied(false);
                                    cts.setReservation(false);
                                    cts.setTask("");
                                    cts.setProblem(null);
                                }
                            }
                        }
                    }
                }
                ts.setOccupied(false);
                ts.setReservation(false);
                ts.setTask("");
                DailySchedule ds = (DailySchedule)dateJComboBox.getSelectedItem();
                populateTable(ds);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_cancelJButtonActionPerformed

    private void backJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backJButtonMouseEntered
        // TODO add your handling code here:
        backJButton.setBackground(Color.ORANGE);
    }//GEN-LAST:event_backJButtonMouseEntered

    private void backJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backJButtonMouseExited
        // TODO add your handling code here:
        backJButton.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_backJButtonMouseExited

    private void cancelJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelJButtonMouseEntered
        // TODO add your handling code here:
        cancelJButton.setBackground(Color.ORANGE);
    }//GEN-LAST:event_cancelJButtonMouseEntered

    private void cancelJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelJButtonMouseExited
        // TODO add your handling code here:
        cancelJButton.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_cancelJButtonMouseExited

    private void viewJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewJButtonMouseEntered
        // TODO add your handling code here:
        viewJButton.setBackground(Color.ORANGE);
    }//GEN-LAST:event_viewJButtonMouseEntered

    private void viewJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewJButtonMouseExited
        // TODO add your handling code here:
        viewJButton.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_viewJButtonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton cancelJButton;
    private javax.swing.JComboBox dateJComboBox;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable scheduleJTable;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JButton viewJButton;
    // End of variables declaration//GEN-END:variables
}
