/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ExaminerRole;

import Business.Application.Application;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *

 */
public class ExamineClientsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ExamineClientsJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount useraccount;
    private Organization organization;
    private EcoSystem system;
    private Network network;
    private Enterprise enterprise;
    private Application application;
    
    public ExamineClientsJPanel(JPanel userProcessContainer, UserAccount useraccount, Organization organization, EcoSystem system, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.useraccount = useraccount;
        this.organization = organization;
        this.system = system;
        this.network = network;
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) examinerTbl.getModel();
        model.setRowCount(0);
        System.out.println(organization.getApplicationDirectory().getApplicationList().size());
        for (Application a : organization.getApplicationDirectory().getApplicationList()){
            Object[] row = new Object[4];
            row[0] = a;
            row[1] = a.getLname();
            row[2] = String.valueOf(a.getIncome());
            row[3] = a.getProblemDescription();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        examinerTbl = new javax.swing.JTable();
        examineBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        problemDescriptionTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fnameTxt = new javax.swing.JTextField();
        mnameTxt = new javax.swing.JTextField();
        lnameTxt = new javax.swing.JTextField();
        aline1Txt = new javax.swing.JTextField();
        cityTxt = new javax.swing.JTextField();
        stateTxt = new javax.swing.JTextField();
        acceptBtn = new javax.swing.JButton();
        declineBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        imageLbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 236, 236));

        examinerTbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        examinerTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Income", "Problem Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(examinerTbl);

        examineBtn.setBackground(new java.awt.Color(51, 51, 51));
        examineBtn.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        examineBtn.setForeground(new java.awt.Color(0, 153, 153));
        examineBtn.setText("View");
        examineBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                examineBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                examineBtnMouseExited(evt);
            }
        });
        examineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examineBtnActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 153));
        jLabel12.setText("Problem Description");

        problemDescriptionTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        problemDescriptionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                problemDescriptionTxtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Middle Name");

        jLabel4.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Last Name");

        jLabel5.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Address");

        jLabel7.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("City");

        jLabel8.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("State");

        fnameTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameTxtActionPerformed(evt);
            }
        });

        mnameTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lnameTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        aline1Txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cityTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        stateTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        acceptBtn.setBackground(new java.awt.Color(51, 51, 51));
        acceptBtn.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        acceptBtn.setForeground(new java.awt.Color(0, 153, 153));
        acceptBtn.setText("Approve");
        acceptBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                acceptBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                acceptBtnMouseExited(evt);
            }
        });
        acceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptBtnActionPerformed(evt);
            }
        });

        declineBtn.setBackground(new java.awt.Color(51, 51, 51));
        declineBtn.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        declineBtn.setForeground(new java.awt.Color(0, 153, 153));
        declineBtn.setText("Decline");
        declineBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                declineBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                declineBtnMouseExited(evt);
            }
        });
        declineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineBtnActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back Button Arrow Icon!!!! (3).jpg"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        jLabel11.setBackground(new java.awt.Color(51, 0, 0));
        jLabel11.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("APPLICATIONS");
        jLabel11.setFocusTraversalPolicyProvider(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(imageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(examineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(declineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(problemDescriptionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(stateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(aline1Txt))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aline1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(problemDescriptionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(examineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(acceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(declineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(imageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        problemDescriptionTxt.getAccessibleContext().setAccessibleName("");
        fnameTxt.getAccessibleContext().setAccessibleName("");
        mnameTxt.getAccessibleContext().setAccessibleName("");
        lnameTxt.getAccessibleContext().setAccessibleName("");
        aline1Txt.getAccessibleContext().setAccessibleName("");
        cityTxt.getAccessibleContext().setAccessibleName("");
        stateTxt.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void examineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examineBtnActionPerformed
        // TODO add your handling code here:
        examinerTbl.setColumnSelectionAllowed(false);
        examinerTbl.setRowSelectionAllowed(true);
        fnameTxt.setEditable(false);
        mnameTxt.setEditable(false);
        lnameTxt.setEditable(false);
        aline1Txt.setEditable(false);
//        aline2Txt.setEditable(false);
        cityTxt.setEditable(false);
        stateTxt.setEditable(false);
//        zipTxt.setEditable(false);
//        incomeTxt.setEditable(false);
        problemDescriptionTxt.setEditable(false);
//        numberTxt.setEditable(false);
        int selectedRow = examinerTbl.getSelectedRow();
        if (selectedRow >= 0){
        Application a = (Application)examinerTbl.getValueAt(selectedRow,0);
        fnameTxt.setText(a.getFname());
        mnameTxt.setText(a.getMname());
        lnameTxt.setText(a.getLname());
        aline1Txt.setText(a.getAline1());
//        aline2Txt.setText(a.getAline2());
        cityTxt.setText(a.getCity());
        stateTxt.setText(a.getState());
//        zipTxt.setText(convertInteger(a.getZip()));
//        incomeTxt.setText(convertInteger(a.getIncome()));
        problemDescriptionTxt.setText(a.getProblemDescription());
//        numberTxt.setText(convertInteger(a.getNumber()));
        ImageIcon icon = new ImageIcon((a.getPicturePath()));
        icon.setImage(icon.getImage().getScaledInstance(162, 102, Image.SCALE_DEFAULT));
        imageLbl.setIcon(icon);
        }
        else JOptionPane.showMessageDialog(null, "Please Select any row");                                             
    }//GEN-LAST:event_examineBtnActionPerformed

    public static String convertInteger(int i) {
        return Integer.toString(i);
    }
    
    private void problemDescriptionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_problemDescriptionTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_problemDescriptionTxtActionPerformed

    private void fnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameTxtActionPerformed

    private void acceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptBtnActionPerformed
        // TODO add your handling code here:
        String message = "Application Approved";
        JOptionPane.showMessageDialog(null, "Application Approved");

        int selectedRow = examinerTbl.getSelectedRow();
        Application a = (Application)examinerTbl.getValueAt(selectedRow,0);
        a.setStatus(message);
        fnameTxt.setText("");
        lnameTxt.setText("");
        mnameTxt.setText("");
        aline1Txt.setText("");
//        aline2Txt.setText("");
        cityTxt.setText("");
        stateTxt.setText("");
//        zipTxt.setText("");
        problemDescriptionTxt.setText("");
//        incomeTxt.setText("");
//        numberTxt.setText("");
        imageLbl.setText("");
        
        fnameTxt.setEditable(true);
        lnameTxt.setEditable(true);
        mnameTxt.setEditable(true);
        aline1Txt.setEditable(true);
//        aline2Txt.setEditable(true);
        cityTxt.setEditable(true);
        stateTxt.setEditable(true);
//        zipTxt.setEditable(true);
//        incomeTxt.setEditable(true);
        problemDescriptionTxt.setEditable(true);
//        numberTxt.setEditable(true);
    }//GEN-LAST:event_acceptBtnActionPerformed

    private void declineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineBtnActionPerformed
        // TODO add your handling code here:
        String message = "Application Declined";
        JOptionPane.showMessageDialog(null, "Application Declined");
        int selectedRow = examinerTbl.getSelectedRow();
        Application a = (Application)examinerTbl.getValueAt(selectedRow,0);
        a.setStatus(message);
    }//GEN-LAST:event_declineBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.userProcessContainer.remove(this);
        CardLayout layout= (CardLayout)this.userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void examineBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_examineBtnMouseEntered
        // TODO add your handling code here:
        examineBtn.setBackground(Color.ORANGE);
    }//GEN-LAST:event_examineBtnMouseEntered

    private void examineBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_examineBtnMouseExited
        // TODO add your handling code here:
        examineBtn.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_examineBtnMouseExited

    private void acceptBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acceptBtnMouseEntered
        // TODO add your handling code here:
        acceptBtn.setBackground(Color.ORANGE);
    }//GEN-LAST:event_acceptBtnMouseEntered

    private void acceptBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acceptBtnMouseExited
        // TODO add your handling code here:
        acceptBtn.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_acceptBtnMouseExited

    private void declineBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_declineBtnMouseEntered
        // TODO add your handling code here:
        declineBtn.setBackground(Color.ORANGE);
    }//GEN-LAST:event_declineBtnMouseEntered

    private void declineBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_declineBtnMouseExited
        // TODO add your handling code here:
        declineBtn.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_declineBtnMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptBtn;
    private javax.swing.JTextField aline1Txt;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField cityTxt;
    private javax.swing.JButton declineBtn;
    private javax.swing.JButton examineBtn;
    private javax.swing.JTable examinerTbl;
    private javax.swing.JTextField fnameTxt;
    private javax.swing.JLabel imageLbl;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lnameTxt;
    private javax.swing.JTextField mnameTxt;
    private javax.swing.JTextField problemDescriptionTxt;
    private javax.swing.JTextField stateTxt;
    // End of variables declaration//GEN-END:variables
}
